CREATE TABLE Aktiehandel
(
	HandelsId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Navn NCHAR(10) NOT NULL,
	Antal INT NOT NULL,
	Handelspris FLOAT NOT NULL
)

CREATE TABLE Aktiehandel
(
	HandelsId INT NOT NULL PRIMARY KEY,
	Navn NCHAR(10) NOT NULL,
	Antal INT NOT NULL,
	Handelspris FLOAT NOT NULL
)

DROP TABLE Aktiehandel;
